sudo: required

language: node_js

services:
  - redis-server

cache:
  directories:
    - node_modules

node_js:
  - '8'
  - '10'

notifications:
  email:
    recipients:
      - nnsceg@gmail.com
    on_success: never
    on_failure: always

branches:
 except:
   - /^v\d+\.\d+\.\d+$/

script:
  - npm run cover
after_success:
  - npm run report-coverage
